-- MySQL Script generated by MySQL Workbench
-- Sat Mar 28 20:32:17 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_venda` (
  `id_item_venda` INT NOT NULL AUTO_INCREMENT,
  `id_venda` INT NOT NULL,
  `id_livro` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_item_venda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `data_venda` DATETIME NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `desconto` DECIMAL(10,2) NULL,
  `id_usuario` INT NOT NULL,
  `id_cliente` INT NULL,
  `item_venda_id_item_venda` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_item_venda1_idx` (`item_venda_id_item_venda` ASC) VISIBLE,
  CONSTRAINT `fk_venda_item_venda1`
    FOREIGN KEY (`item_venda_id_item_venda`)
    REFERENCES `mydb`.`item_venda` (`id_item_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mov_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mov_estoque` (
  `id_movimentacao` INT NOT NULL AUTO_INCREMENT,
  `id_livro` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  `quantidade` INT NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `observacao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_movimentacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `perfil` VARCHAR(20) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `venda_id_venda` INT NOT NULL,
  `mov_estoque_id_movimentacao` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  INDEX `fk_usuario_venda_idx` (`venda_id_venda` ASC) VISIBLE,
  INDEX `fk_usuario_mov_estoque1_idx` (`mov_estoque_id_movimentacao` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_venda`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `mydb`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_mov_estoque1`
    FOREIGN KEY (`mov_estoque_id_movimentacao`)
    REFERENCES `mydb`.`mov_estoque` (`id_movimentacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `clube_vantagens` TINYINT(1) NOT NULL,
  `venda_id_venda` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_cliente_venda1_idx` (`venda_id_venda` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_venda1`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `mydb`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livro` (
  `id_livro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(150) NOT NULL,
  `isbn` VARCHAR(20) NOT NULL,
  `autor` VARCHAR(100) NOT NULL,
  `editora` VARCHAR(100) NULL,
  `genero` VARCHAR(50) NULL,
  `ano_publicacao` INT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `quantidade_estoque` INT NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `item_venda_id_item_venda` INT NOT NULL,
  `mov_estoque_id_movimentacao` INT NOT NULL,
  PRIMARY KEY (`id_livro`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE,
  INDEX `fk_livro_item_venda1_idx` (`item_venda_id_item_venda` ASC) VISIBLE,
  INDEX `fk_livro_mov_estoque1_idx` (`mov_estoque_id_movimentacao` ASC) VISIBLE,
  CONSTRAINT `fk_livro_item_venda1`
    FOREIGN KEY (`item_venda_id_item_venda`)
    REFERENCES `mydb`.`item_venda` (`id_item_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_mov_estoque1`
    FOREIGN KEY (`mov_estoque_id_movimentacao`)
    REFERENCES `mydb`.`mov_estoque` (`id_movimentacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
